### ISSUE TITLE
Option to update primary email address

### ISSUE THREAD

**Issue by bkowshik** [hasgeek/funnel#193] opened 2017-07-03 05:21 UTC
*NOTE: I faced this issue myself. Posting here just in case other users have similar issues*

---

A users profile page lists one or more email addresses with one among them tagged `primary`.
- https://auth.hasgeek.com/profile

There isn't an option to make a second email address as `primary`. Trying the `remove` email address option on the primary email gives the following notification.

> You cannot remove your primary email address 

This would make it hard for users who want to keep an existing `username` but modify the email addresses. Ex: A user who signed up using work email but later changes jobs and has a new work email.

**Comment by jace** [comment] 2017-07-03 05:33
Dupe of hasgeek/lastuser#35. Mail us at support@hasgeek.com for now. This ticket should be resolved within a month.

**Closed by jace** 2017-07-03 05:33 UTC

**Comment by jace** [comment] 2018-10-01 18:40
This was implemented in hasgeek/lastuser#233 and is now live. Visit https://auth.hasgeek.com/account.
