### ISSUE TITLE
Corrupted Content Error

### ISSUE THREAD

**Issue by anandology** [hasgeek/funnel#503] opened 2019-09-16 22:22 UTC
I've seen this error couple of times today. 

```
The site at https://hasgeek.com/jsfoo/2019/schedule/how-cloudcherry-built-a-world-class-angular-app-SnsiPrVVqw2Z8hTF7y9MCg has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the website owners to inform them of this problem.
```

![Screen Shot 2019-09-17 at 3 50 32 AM](https://user-images.githubusercontent.com/7569/64997431-545a2f00-d8fe-11e9-8344-f583a56bba05.png)

## How to Reproduce

* Go to https://hasgeek.com/jsfoo/2019/proposals/how-cloudcherry-built-a-world-class-angular-app-pCwddyLNXBR2V234QMxKk8
* Click on "View proposal in schedule"

**Comment by jace** [comment] 2019-09-17 08:46
I'm unable to reproduce this in Chrome. @vidya-ram can you check with Firefox? @anandology is there any browser extension that could possibly be interfering? It'll help to isolate the source of the malfunction.

**Comment by anandology** [comment] 2019-09-17 09:02
Unable to reproduce it now. I was able to reproduce it consistently in the morning using Firefox.

**Comment by jace** [comment] 2019-09-19 14:49
Okay, closing this for now. Please reopen if you spot it again.

**Closed by jace** 2019-09-19 14:49 UTC
